import { Inter } from 'next/font/google';
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Template Next.js App',
    description: 'Generated by create next app',
};

import { ThemeProvider } from '@/components/theme-provider';
import { LocalStorageProvider } from '@/hooks/use-local-storage';
import { StoreProvider } from '@/hooks/use-store';
import Navbar from '@/components/Navbar.jsx';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider>
                    <StoreProvider>
                        <LocalStorageProvider>
                            <Navbar />
                            <main className="flex min-h-screen flex-col items-center justify-between px-2 sm:px-12 md:px-24 pt-5">
                                {children}
                            </main>
                        </LocalStorageProvider>
                    </StoreProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
